---
apiVersion: codemowers.cloud/v1beta1
kind: OIDCClient
metadata:
  name: memelord-{{ .Release.Name }}
spec:
  displayName: Memelord {{ .Release.Name }}
  uri: https://{{ .Values.hostname }}.{{ .Values.domain }}/
  redirectUris:
    - https://{{ .Values.hostname }}.{{ .Values.domain }}/oidc/callback/
  grantTypes:
    - authorization_code
    - refresh_token
  responseTypes:
    - code
  availableScopes:
    - openid
    - profile
  pkce: false
